version: "3.3"

services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    volumes:
      - ./src/stardew_web.sql:/docker-entrypoint-initdb.d/stardew_web.sql
    networks:
      - mynet

  myredis:
    image: redis:latest
    networks:
      - mynet

  myphp:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - myredis
    networks:
      - mynet
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  mynginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - myphp
    networks:
      - mynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports: 
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - mynet

networks:
  mynet:
    driver: overlay
